### ISSUE TITLE
Fix the use `@_implementationOnly` in SwiftWasm Foundation

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#2110]
We have some changes in the `swiftwasm` branch when compared to upstream with regards to `@_implementationOnly` in Foundation code. It should be applied consistently, otherwise it would require users to add `import CoreFoundation` for their code to work, which is undesirable.

**Comment by MaxDesiatov** [comment]
@kateinoigakukun I've only put my superficial understanding of it in the description. Is that close to what you've described in https://github.com/swiftwasm/carton/pull/141?

**Comment by kateinoigakukun** [comment]
There is no change around use of `@_implementationOnly` between our fork and upstream. And upstream has a misuse of the attribute.

If there is any import statement which imports module A and is attributed with `@_implementationOnly`, all imports for module A in the module should have the attribute and module A won't be linked automatically.

Most of CoreFoundation imports in Foundation are attributed with `@_implementationOnly`, but only RunLoop.swift have an import without the attribute and It causes warnings. In addition, that triggers autolinking Foundation. So Linux toolchain doesn't require explicit CoreFoundation import when importing Foundation.

But our forked doesn't have RunLoop.swift, so autolink is not triggered and explicit import is required.

I'm not confident the explicit CoreFoundation import is expected behavior, so I'll ask it in forum.

**Comment by kateinoigakukun** [comment]
Asked https://forums.swift.org/t/implementationonly-behavior-in-autolinking/41621

**Comment by MaxDesiatov** [comment]
@kateinoigakukun can this be closed as resolved?

**Comment by kateinoigakukun** [comment]
Yes, it's already resolved
