### ISSUE TITLE
Cannot import FoundationNetworking

### ISSUE THREAD

**Issue by Sajjon** [swiftwasm/swift#2316]
How can I use URLSession? I tried importing `FoundationNetworking` but I can't get it to work.

I use:

```bash
swift --version
SwiftWasm Swift version 5.3 (swiftlang-5.3.0)
Target: x86_64-apple-darwin19.6.0
```

And compilation command: `swift build --triple wasm32-unknown-wasi`

```bash
main.swift:122:35: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
    private lazy var urlSession = URLSession(
```

So then I try:

```swift
import Foundation
import FoundationNetworking

// ... later
let urlSession = FoundationNetworking.URLSession(
        configuration: .default,
        delegate: self,
        delegateQueue: nil
)
```

But that results in

```bash
main.swift:4:8: error: no such module 'FoundationNetworking'
import FoundationNetworking
```

So then I try:

```swift
import Foundation

#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
```

But that results in:

```bash
main.swift:122:35: error: cannot find 'FoundationNetworking' in scope
    private lazy var urlSession = FoundationNetworking.URLSession(
                                  ^~~~~~~~~~~~~~~~~~~~
```

**Comment by MaxDesiatov** [comment]
Thanks for creating the issue @Sajjon. I've updated [the SwiftWasm book chapter about Foundation](https://book.swiftwasm.org/getting-started/foundation.html) to explicitly mention `FoundationNetworking` as unsupported. The reason is that browsers (and currently WASI too) don't provide access to raw sockets, which is what libcurl (and Swift NIO as a potential replacement for libcurl) requires, and FoundationNetworking is built upon those.

If making HTTP requests is something you're looking for, I recommend checking out [OpenCombineJS](https://github.com/swiftwasm/OpenCombineJS#example), which can convert `JSPromise` instances returned from the `fetch` browser API to proper OpenCombine publishers, and those are easier to interact with.

**Comment by Sajjon** [comment]
Thanks your prompt reply! I was hoping to have a complete Swift codebase (with networking in place) that I could just compile to WebAssembly using SwiftWasm. 

So your suggestion is not a feasible solution for me, and looks like I won't be able to achieve my goal just yet. Hopefully networking matures in WebAssembly land (and thus becomes ready for use with SwiftWasm).

I applaud all your efforts with the SwiftWasm project, it really is amazing! Imagine Swift possibly someday being the language "of the web" 😍

**Comment by Sajjon** [comment]
Will close this issue for now, thanks!

**Comment by MaxDesiatov** [comment]
> Hopefully networking matures in WebAssembly land

This is not a problem specific to WebAssembly, browsers have to implement a raw socket API first so that we can bridge it. There's nothing that prevents us from bridging it to WebAssembly if browsers supported this.

**Comment by Sajjon** [comment]
> browsers have to implement a raw socket API first
Ah, ok thanks! Sorry, I'm a complete web and WASM n00b so I have difficulties distinguishing between what's what and how each entity relate to an another (Swift, SwiftWasm, WebAssembly, Wasmer, Browsers...) 🤪 

Btw, how close do you think we are for Apple to accept the work being doing in this Swift fork? And adopting SwiftWasm in the upstream ([github.com/apple/swift](https://github.com/apple/swift))? Like 6 months, 1 year, 2 years? Impossible to say with accuracy of course, but what is your personal guess @MaxDesiatov ? :) Because the other day I saw that [the Apple Documentation for `Platform` in SPM includes `wasi`](https://developer.apple.com/documentation/swift_packages/platform/3583305-wasi)!

**Comment by MaxDesiatov** [comment]
We upstreamed 95% of our changes to SwiftPM, the majority of remaining changes are in the toolchain and in the SDK (runtime, stdlib, Foundation etc).

I can't give any estimates, it's completely up to Apple. For example, our major PR https://github.com/apple/swift/pull/33400 is stuck in the review queue since August with no visible progress. Only people who review our PRs would be able to give such estimate.

**Comment by j-f1** [comment]
While it wouldn’t be possible to use FoundationNetworking as-is, it should be possible to implement at least some of its (HTTP-based) APIs by wrapping JavaScript’s `fetch` API.

**Comment by MaxDesiatov** [comment]
Possibly, but the problem is that Foundation is a "core" library that's part of the SDK distributed with the toolchain. We'd need to do the same for JavaScriptKit, which is blocked by https://github.com/swiftwasm/JavaScriptKit/issues/61.
