### ISSUE TITLE
Foundation attempts to read from `/dev/urandom`

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#2605]
It was discovered by @kateinoigakukun. See [this line](https://github.com/swiftwasm/swift-corelibs-foundation/blob/ccb3172f48281af337d9cd4ce925ff0098853345/Sources/UUID/uuid.c#L92-L96), which causes exceptions on WASI.

**Comment by j-f1** [comment]
This can be fixed by implementing a platform-specific version of `read_random` using [`random_get`](https://github.com/WebAssembly/WASI/blob/89562f904b23cd0df07583b8947ca42c65b2f8a8/phases/snapshot/docs.md#-random_getbuf-pointeru8-buf_len-size---errno). It might be as simple as `#define read_random random_get`.

**Comment by kateinoigakukun** [comment]
This is also resolved by https://github.com/swiftwasm/swift-corelibs-foundation/pull/323

**Comment by MaxDesiatov** [comment]
Is there any substantial difference between `getentropy` and `random_get`? Why would we use one over the other?

**Comment by kateinoigakukun** [comment]
getentropy internally use get_random. https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/sources/getentropy.c

getentropy is more portable API than wasi specific get_random, so I used it.
