### ISSUE TITLE
Question about Resources

### ISSUE THREAD

**Issue by SDGGiesbrecht** [swiftwasm/swift#4529]
I discovered that SwiftPM’s [generated resource accessor is tailored for WASI](https://github.com/apple/swift-package-manager/blob/0147f7122a2c66eef55dcf17a0e4812320d5c7e6/Sources/Build/BuildPlan.swift#L737-L743). Is this feature complete? How are the resources intended to be located and loaded? (The `url(forResource:extension:)` method used by the other platforms is unavailable.)

**Comment by MaxDesiatov** [comment]
Resources are located and loaded via `carton dev` web server, which was implemented in this PR https://github.com/swiftwasm/carton/issues/38. Additionally, `carton bundle` copies these resources to the `Bundle` directory so that production servers can provide these resources at paths that client code expects them to be located. Other than that, there's no additional WASI-specific support for resources, to my knowledge.

Does that answer your question?

**Comment by MaxDesiatov** [comment]
Important to note, there are still limitations with support for resources in `carton`, see https://github.com/swiftwasm/carton/issues/175.

**Comment by SDGGiesbrecht** [comment]
Yes, I just got confused because I reached for `url(forResource:withExtension:)` first instead of `path(forResource:ofType:)` and the former did not exist. I realized the difference when I saw the test in the PR you linked. Thanks.
