### ISSUE TITLE
Reproducible .wasm file builds

### ISSUE THREAD

**Issue by kennu** [swiftwasm/swift#4772]
While I was building .wasm files with various languages (AssemblyScript, C, C++, C#, Go, Grain, Haskell, Motoko, Rust, Zig), I noticed that Swift is the only one that generates a different .wasm file after every build.

In practice, if you store .wasm files in Git or otherwise rely on change detection, you get a new version after every build, even if the source code didn't change.

This is not a big problem for me, but I thought I'd mention it, since it appears to be unique to Swift. Please feel free to close the issue if it's out of scope of the project.

**Comment by kennu** [comment]
With a hex dump, the difference is somewhere deep in the middle of the .wasm files:

    diff 1.txt 2.txt       
    295713c295713
    < 22154160 20 fc 5f a5 fa 0f ef 97 26 dd cf b7 b2 d7 e9 60
    ---
    > 22154160 e5 3b 7a d5 5b e6 4a 9e 7d 2f f0 d9 03 35 15 c5

**Comment by ephemer** [comment]
I'm curious whether this also occurs during release builds?

**Comment by gregcotten** [comment]
@ephemer 

Answer: yes

**Comment by kateinoigakukun** [comment]
`--gc-sections` support resolved this issue https://github.com/swiftwasm/swift/issues/5128 because it enabled GCing `.swift_modhash` section which is always unused at runtime. I've confirmed `swift build` emits exactly same  binaries for the same inputs with the latest nightly toolchain https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-01-a
